### ISSUE TITLE
Compiling problems when adding a new ADC channel in CubeMx

### ISSUE THREAD

**Issue by francesco-gomez-ur1** [danak6jq/RAK3172#8]
I need to read an external voltage, so I activated adc IN3 on PB4 form CubeMX (v 6.7) (with CubeIDE v 1.10) and regenerated the code.
After that the compiler complains about a missing include "adc_if.h" (see below)
Do you have any suggestions to solve the issue ?
...
arm-none-eabi-gcc "../Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_cortex.c" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DCORE_CM4 -DUSE_HAL_DRIVER -DSTM32WLE5xx -c -I../Core/Inc -I../Drivers/BSP/STM32WLxx_Nucleo -I../Drivers/STM32WLxx_HAL_Driver/Inc -I../Drivers/STM32WLxx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../Drivers/CMSIS/Include -I../LoRaWAN/App -I../LoRaWAN/Target -I../Utilities/trace/adv_trace -I../Utilities/misc -I../Utilities/sequencer -I../Utilities/timer -I../Utilities/lpm/tiny_lpm -I../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../Middlewares/Third_Party/SubGHz_Phy -I../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../Middlewares/Third_Party/LoRaWAN/Crypto -I../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../Middlewares/Third_Party/LoRaWAN/Mac -I../Middlewares/Third_Party/LoRaWAN/LmHandler -I../Middlewares/Third_Party/LoRaWAN/Utilities -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_cortex.d" -MT"Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_cortex.o" --specs=nano.specs -mfloat-abi=soft -mthumb -o "Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_cortex.o"
../LoRaWAN/App/lora_app.c:34:10: fatal error: adc_if.h: No such file or directory
   34 | #include "adc_if.h"
      |          ^~~~~~~~~~
compilation terminated.
...

**Comment by danak6jq** [comment]
On the master branch, I can add '#include "adc_if.h"' to lora_app.c and compile successfully.
I then added IN3 is Cube, regenerated, and see this:

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   ../../.mxproject
        modified:   ../../.settings/language.settings.xml
        modified:   ../../.settings/stm32cubeide.project.prefs
        deleted:    ../../Core/Inc/adc_if.h
        modified:   ../../Core/Src/adc.c
        deleted:    ../../Core/Src/adc_if.c
        modified:   ../../RAK3172.ioc
        modified:   ../../STM32WLE5CCUX_FLASH.ld

So - yes, adc_if.h is removed! What _could_ cause this? It turns out, one of the Cube "Middleware > LoRaWAN" options is the culprit. Specifically, when you change the ADC configuration in Cube, it resets the "Platform Settings > Vrefint Channel" to "undefined" - you need to re-select "ADC" for this there. 

You'll get a successful build then. CubeMX is just trying to keep you on your toes!


<img width="310" alt="image" src="https://user-images.githubusercontent.com/942815/214765483-312e1db5-de8e-428e-a141-363c9fc29a9a.png">
<img width="313" alt="image" src="https://user-images.githubusercontent.com/942815/214765741-770df6bc-d25b-4e46-b4f1-f7fad4ea7eea.png">

**Comment by francesco-gomez-ur1** [comment]
Thank you very much, danak6jq !
I can now use the ADC even if I must do that manual adjustment.
You did a great and job in porting and maintaining this Lora node project on cubeMX 
I greatly appreciate it and the kind support you gave me :)

**Comment by danak6jq** [comment]
Thank you @francesco-gomez-ur1 ! Happy to help. I think ST triggers a reset of the LoRaWAN application ADC setting when any change is made to the ADC component to make sure the developer checks for side-effects on the LoRaWAN app. At least that's my guess.
